
COPY ./target/webapps/ /usr/local/tomcat-base/webapps/
COPY ./target/components/ /usr/local/tomcat-base/components/
COPY ./target/lib/ /usr/local/tomcat-base/lib/
COPY ./bin/ /usr/local/tomcat-base/bin/
COPY ./conf/ /usr/local/tomcat-base/conf/
COPY ./security/mysql.properties /usr/local/tomcat-base/security-mysql/security.properties
COPY ./security/oracle.properties /usr/local/tomcat-base/security-oracle/security.properties
COPY ./security/mariadb.properties /usr/local/tomcat-base/security-mariadb/security.properties
